language: ruby
rvm:
  - 2.1

sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install pandoc

install: bundle install
script: bundle exec jekyll build  

# branch whitelist, only for GitHub Pages
branches:
    only:
        - master     # test the gh-pages branch

env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
