language: ruby
rvm:
- 2.1
sudo: false
addons:
  apt:
    packages:
    - pandoc
before_script:
- chmod +x deploy.sh
install: bundle install
script: bundle exec jekyll build
after_script: "./deploy.sh"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: REi1D/u32iOp1ODiCxTNAL9oU96nv3nEzcwbZ5VE3XVB1zsmcjk8iin8CXORpSJSX5h4dRlchi9l9k2YdkL5LJMtv4hITKD/HDRXRB+Qx8YHI0UeXZSsv/u55VQmhFqHqH+aKc0/FTDDjAWykm0ryl2qc6RSsUnUHNjlMCjHL45Rx0nEVCcJ0bFxSE7acdaEw8gTXmYbaxHoAzVJv7ys3/ticMS5D6tRTS+Tg3lmjrxj9P9haEEQggbVwvsMDWKmv5HWmdJdAbsnnHTq4j2HmIiiTPGtOoxBlYs5a450FxQT+2+Gllztj1A/jiNcjBc46D2T/hMZdieNZENmgeZX4sUZembT/YnW7OWEXFbL6OW4j/QgXFGXcQ2GnMlLQ33orp//y022H+YjPo0nhgQX/cejYnKvG07nAMndfmmMobZD+NB8FuMghfjrZeBPg4d5sxFqyEPGWUIDPvQmXurnCIlqrdF6jHOiHledlE+YXsG+VqD3OzWiWNn1L1VBiAA7Wf1NEQ5vrSF2lhCykNiRGdE+O7WL1iOvteDD8K/osrcNQ06Sso2xN3tx1/n4Ar7kvCTJ+Ut+4S4cAeBej921g7r9rNN4GRaKatURUxtZ1En644PyffBFRFy4OzUoGr0doE+prQg7W/0UvWD7LJBznuwioYmVBOC1uyoluTFB7x4=
  - secure: JsKSItooc1uezqcNDVs09USokPMhtzGapFRl37REY8e14NsRnmfGoZuBkWXjx7oSXki4UcqUOfD6Cjm2mTCOc1zDkQWgb8/Wib4yDpFCUwF06N4IeWNpvak3NDzIduwB9dHHDbkOu2fv75TySBZME4fNhSx6ti0Snjn61vcfrS88wBuVCJajDSgdu/ray0V/vOO70aDn7yLgR+LzA0B7bpukuLVPOcCeWZwwVjnsDTw8IxfjKoHKOb9x/gEqs/a5HLHDjyfkQJQ9ZGT6NJlRsje3jOzHZBtAAl/wXFpJjvc6yZWk/lewpcNLLdh98XoZoI0IdT4dLmX3Tg3zh0gPNhZiSyLhuuC9KbJ4IiAICmp1PAalJ3ARBEZDvyMkLUmnoUEcjqvdglZSSCswYkbgoeuJPe4AGgB3RG/wfPH10yDrjplWB2g2CFveEnqUdD0Q+A5SuomOtBYA+0PDzQf8NIy9O0+3PzIl+s9nIMtmH8FU1wL+vd2icHbfdkh9lWSpqSwBLtVXAhR6tB1+9Z8dbCtwwBHE4RPjbRrmTRYGKsc1SxQpaLzz9ik1s6lcou6wlb93vK/7NsDxPnl8q/qrfOzao/5lVwn/n3P5y4m5mYU0/5EDvFcY0+eCLwK2yLvB4SZ/Pt2pOJgmhLjUzzhm4v/LHk/2rbvsOOcJawOHO0Q=
