language: ruby
rvm:
  - 2.1

sudo: false
addons:
  apt:
    packages:
    - pandoc

before_script:
 - chmod +x deploy.sh
install: bundle install
script: bundle exec jekyll build  
after_script: ./deploy.sh

# branch whitelist, only for GitHub Pages
branches:
    only:
        - master     # test the gh-pages branch

env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
