language: haskell

branches:
  only:
    - master

sudo: false
addons:
  apt:
    packages:
    - pandoc
    - pandoc-citeproc

install:
  - travis_retry bundle install

script:
  # - bundle exec jekyll build
  #  - echo -e $twitter > _twitter.yml
  #  - echo -e $twitter2 >> _twitter.yml
  #  - echo -e $twitter3 >> _twitter.yml
  #  - echo -e $garb > _garb.yml
  #  - echo -e $garb2 >> _garb.yml
  - bundle exec rake site:deploy --quiet
  #  - rm -f _twitter.yml _garb.yml

env:
  global:
  - secure: hkMBU1M3g86rDj/sDeMQfn8F/2pG++uDmEp4DaVfk47jJ2dtn7oKRWNXJBXsl8zFrxblM4GSlzZMAD8hALrDAZ5Yp7tcRXPF5upx7GfE7OJq4sWbOvaQQZS4ZyKDDd4pl3Ik6cQYQzAgMxRY4D5vTFRBFWTa7+E3F8Ps4Lsc6sgS3utadvP2E0YJCLosvHjS7N85OaylK0lZflgHKIXULRRBgz0Swz+NBDb0VqbqXwiEE1uoZv4fLVb++5M6S0Hwc5yYr5Rc9Ti7M+k+GghWpS61JOuEpvd6wHnf+nUQQhX155eOmAByiJV7dva4/44fzfy8v4EYVjfvRMgCG8jLTEzWQhhLu7wrc8zNwpa3VX5qc2txRGdvQe6UDSYCsf9cOsM7Sw1sh8GbwUOTeBv86qG4QiWuXteeH9lTTFwk58Ea3BGvi0/XW413z92jcmXiHv5qJizIsjlbNjygPPfdXLG0WACy3wzBauS45OxI0YzX+JEO20LLorIIoUagykm7Q7eFqmSKu1g/DJeswIHZ56k1OCoWFDgEZUp0xK19ElaSVRtNmwUOL+JmLu6NJHkWpmQ6t9U7ECHyhsq8jqFnYJ1SEhMlEXPp2s27GUX+pyb61Hw0O4+3gmcrdZU//PjoTzwNF+JzjcrCzcITluhpUdSf8kkrijUOH78JH5GNPA8=
