language: ruby
rvm:
  - 2.1

# branch whitelist, only for GitHub Pages
branches:
    only:
        - master     # test the gh-pages branch

sudo: false
addons:
  apt:
    packages:
    - pandoc

before_script:
 - git config --global user.email "marco@rizzoli.me.uk"
 - git config --global user.name "mrizzoli"
 
install: bundle install
script: 
  - bundle exec jekyll build  
  #- bundle exec rake site:deploy --quiet
  - cd _site
  - git init
  - git remote add origin https://mrizzoli:${GH_TOKEN}@github.com/mrizzoli/notes_src.git
  - git checkout -b gh-pages
  - git add --all
  - git commit -m "automatic travis update"
  - git push origin gh-pages
  - echo "sembra tutto a posto"
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: JsKSItooc1uezqcNDVs09USokPMhtzGapFRl37REY8e14NsRnmfGoZuBkWXjx7oSXki4UcqUOfD6Cjm2mTCOc1zDkQWgb8/Wib4yDpFCUwF06N4IeWNpvak3NDzIduwB9dHHDbkO$
