language: ruby
rvm:
  - 2.1

# branch whitelist, only for GitHub Pages
branches:
    only:
        - master     # test the gh-pages branch

sudo: false
addons:
  apt:
    packages:
    - pandoc

before_script:
 - git config --global user.email "marco@rizzoli.me.uk"
 - git config --global user.name "mrizzoli"
 
install: bundle install
script: 
  - bundle exec jekyll build  
  #- bundle exec rake site:deploy --quiet
  - cd _site
  - git init
  - git remote add origin https://e5dfd02c4fc643905a0265f332ce4157d8814e24@github.com/mrizzoli/notes_src.git
  - git checkout -b gh-pages
  - git add --all
  - git commit -m "automatic travis update"
  - git push origin gh-pages
  - echo "sembra tutto a posto"
  
env:
  global:
  - secure: "U/DLO5iVFC99OVMbEdGblWuN2SPtBLBN+G3MEixkNy+0B0tXBW6fFuH3H6NPQxhlIcTKb5f6a654LtTFmEL456YYJetvYyvUteHw/uKK37/f0AERrbQmcuEoT+OBaEuUfWiD83HvPloL8Dr8IJ/c+jNljDQlwikN/hjhY/lYpO2uV74zk+RGv6XqyH7vJlDJoSNitz38I+PYgAixAChpZg/l1/mSPDlcmJFbtFirAfxyf5c4JCLxhZHqQOW4GdpS0+Kjc7J0pzmXNyg/V7nzg76SUHdevecJVjv52WjLmlxcykZM0gdrM5tKQ3YNgwKSpu35EahlQS4VFFhUg2WrZiEqztQqK7gw3kxHAzJQyCKr+Kh6A88QdXPKA1qW5A68ByYa3h45rzyhkKVDyq4CPWQatS7H0ZiyuNMspWrcZsWBLWAvO/Cm1plv3qAJD+hd4RjaAQTFtDh3vpwRL3wxekupsa0ydsatXHu5eidCwujFw8/m11zPpvCtEzIkP1JEJm6nUr78LZTycdxBB58e6lSRoup+ZMpqn5LD7ZF4NmZmHaO5oUWE8BxfZexc2k6XOdH5H6HqzDTEewlIBMo1SLzlN33dQaGch5H+SbSmsnCQFA84QyySmByOQyD7d8I9nPgRMTLobKJl/E1kwbjBwZhV1Ul/P1EgVONvvvi0fAI="
  
