language: haskell

branches:
  only:
    - master

sudo: false
addons:
  apt:
    packages:
    - pandoc

install:
  - travis_retry bundle install

script:
  # - bundle exec jekyll build
  #  - echo -e $twitter > _twitter.yml
  #  - echo -e $twitter2 >> _twitter.yml
  #  - echo -e $twitter3 >> _twitter.yml
  #  - echo -e $garb > _garb.yml
  #  - echo -e $garb2 >> _garb.yml
  - bundle exec rake site:deploy --quiet
  #  - rm -f _twitter.yml _garb.yml

env:
  global:
  - secure: jgH/rN3R+3rvD1L2YYXgEMqnkvgZ715DUNEvjMQ05pHqrYQCLOYuvRSELOz6rWqP4wuEK533YU+wLeqoo+HMNiCRDOwh5y9I1kBFBogbfF71k69VOSxg49McNuXqMvtgu/l4nIwWv5n7fYgdtHsqtUP8G9WtMTXliWXU6hO4TDVrS6yFkI9biFlROLSv1GA5/8lHGWdCbSjSpjNlrvjm7T4ecCyWm7Oo22h1zL7ObKgi3muvewB71yKtuibULtAeF0o5GMeylyVSRjp0ztOAJpdqx8UbYTh7wykcXrhr9W9itut4Iln1BAjDXizQQgBc/N0ptWHd3jmym4+F6Krz8/2FNfFmUExHaQ+SBOPIVnaGixDIQZqjK9DT0Ul8gJTfNlWhRR+9rajmJATdIGGZgBjbZIYNM6xcl+jLMKAPxF9XX+1b7oArJMsW9pRRBZlFOsOp+/A5QmM4vjrOfJV4NkEzuYNqdjILhjwF+FUsc6xHIrj83uYYnEGs7msz7TPkmYtgSztbER0lf/eleB5JZge8JVCTIfY/o5aRbTseEbd31KtvVmt21kvTKbqLmvrvUMbvM/CmdcVr3xf1sW9y9Em7SLWjUEnd+Jny+Fl0vAovIVHg0TLiEhkPPa60IEJujpLqKxZifumYJ7bGWarN9Kh3FbraSoxkqjX4fzlFXw4=
