# Jekyll configuration

title: Notes and stuff 
name: Notes and stuff 

author:
givenName: Marco
familyName: Rizzoli
github: mrizzoli
# url: notebook.rizzoli.me.uk

username: mrizzoli
repo: notes_src

scholar:
  style: apa
  sort_by: year
  order: descending
  source: $PWD/biblio
  bibliography: biblio.bib

# Url is currently only used only for the RSS feed in feed.xml
# url: http://notebook.rizzoli.me.uk
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
#baseurl: 'notebook.rizzoli.me.uk'

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: mrizzoli
  stackoverflow: ''
  linkedin:
  instagram: ''
  lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: mrizzoli
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge
plugins:
  - jekyll-pandoc
 

markdown: Pandoc
pandoc:
  extensions:
  - smart
  - bibliography: $PWD/biblio/biblio.bib

exclude: ['README.md', 'LICENSE', Gemfile]
